### ISSUE TITLE
Developer - Diogo Araújo 

### ISSUE THREAD

**Issue by araujodiogo** [MobilityHackLisbon/Find-Your-Team#10]
You can contact me in English or Portuguese.

# Who I am
Hi, my name is Diogo Araújo and currently I am in the last year of my master's in computer engineering @ IST. The main focus of my masters is in cybersecurity, and I am working on my Thesis on Quantum-Resistant Blockchain. In parallel, I work for studentlabpt developing mobile applications with react native. 
I hope to learn with everyone during this event and to have fun doing it !

# What I do
At the moment, professionally, I am working with Javascript and Php, but I also have some experience in java, c# and python. Overall I am confortable working the full stack and always eager to learn new languages and technologies!

Regarding Solidity, I am a complete beginner, I only did a very simple smart contract for a course. Nevertheless, I am a fast learner!

# Let's talk
I am always available, feel free to message me in the slack channel or in linkedin!
Linkedin - https://www.linkedin.com/in/diogoguimaraesaraujo/

**Comment by sabatlisbon** [comment]
Hello @araujodiogo would you be interested in joining our team #16. We think is it a strong idea and another pair of hands , would be a great help. 
Can contact us through slack (sabatlisbon).
