### ISSUE TITLE
I need a Gullwing Mercedes to take my girl out

### ISSUE THREAD

**Issue by alcueca** [MobilityHackLisbon/Find-Your-Team#15]
As a person, and a driver, I want to ditch my car and use mobility services instead.

I want to be able to request the vehicle that I need, at the place where I need it, and be able to drive it for the period I request. I want to be able to specify where I’m going to release the vehicle, as well as any other customizations to the service I might need. I want to receive one or more quotes for this service before accepting a specific deal, and I want all the paperwork to be done online.

# Who we are
Bernardo - Hacker supreme
Connor - Frontend wunderkind
Bradley - Graphics master
Sergio - Startup prodigy
Alberto - The Architect

At MobilitHackLisbon.io we are building our dream. Our goal is for our ideas to become reality.

# What we do
We implement blockchain solutions for enterprises and have fun while we do it.

# What we need
We've got what it takes!

# Let's talk
Reach us out at [first name]@techhq.io.

**Comment by jpinho** [comment]
I'm available to join the team, and I think we can boost the initial idea, by expanding it's reach to the Insurance Realm, something that is very connected to Mercedes Benz, given they are as well Insurance Providers for their ALD/Leasing deals!

The problem with Insurance is that... how can they ensure a car that as so many drivers, where is the proof of who was driving it, surely there are records, but a blockchain solution would bring much more value and "insurance" to the Insurance Companies.

I'm new to blockchain using Hyperledger, seems you have a strong team with me joining i think we could do more. Check my profile here: https://github.com/MobilityHackLisbon/Find-Your-Team/issues/19
