### ISSUE TITLE
Autonomous cars connected with blockchain

### ISSUE THREAD

**Issue by pedromdpereira** [MobilityHackLisbon/Find-Your-Team#4]
[PT]  Sintam-se à vontade para me contactar em português
# Who we are
## Pedro Pereira-Python Developer

- Portuguese
-  20 years
- Mechanical Eng. 3rd year

I really want to learn more about blockchain and I expect the your help to build awesome things!

# What we do
The idea is to build a massive blockchain connecting a lot of cars. With this we can store sensors data from them, ideal for AI training without the disadvantages of storage because of the decentralized nature of the blockchain. This data could also be used for insurance purposes taking in mind that all of the blocks can be traced back. providing all the details of an accident.
On top of this, I would also like to implement a peer-to-peer communication system between the cars, also based on the blockchain theory, in a way that when a car wants to execute a manuver, the others in the proximity can check if is safe. This part is harder, as it require to build local "side chains" for cars near each other. 
I already have some code/ideas on both topics, but I'm really looking forward on your suggestions.
# What we need
The main language is **Python.**
If you know how to program in python and want to learn by doing please hit me up!
Of course having experience would be awesome, but not necessary!

# Let's talk
Use the comments below or send me an email: pedro_md_pereira@outlook.pt

**Comment by luismbo** [comment]
In what sense would the blockchain not have the disadvantages of (cloud?) storage? You'll either have to host your own blockchain nodes or pay someone else (e.g., via transaction fees) to host their own blockchain nodes, right?

Having multiple cars verifying each other's sensors and keeping track of each other is an interesting idea! What's the incentive model here? Why would cars/drivers not collude against other cars/drivers or against insurance companies? The challenge, IIUC, is that sensor readings aren't universally verifiable; relatively few cars will be in a position to perform verifications.

**Comment by pedromdpereira** [comment]
> In what sense would the blockchain not have the disadvantages of (cloud?) storage? You'll either have to host your own blockchain nodes or pay someone else (e.g., via transaction fees) to host their own blockchain nodes, right?
> 
> Having multiple cars verifying each other's sensors and keeping track of each other is an interesting idea! What's the incentive model here? Why would cars/drivers not collude against other cars/drivers or against insurance companies? The challenge, IIUC, is that sensor readings aren't universally verifiable; relatively few cars will be in a position to perform verifications.

Thank you for raising such pertinent questions. Please talk with me at the event so I can clear your doubts.
