### ISSUE TITLE
Developer JS & Solidity - André Pardal

### ISSUE THREAD

**Issue by acpardal** [MobilityHackLisbon/Find-Your-Team#5]
Hi, my name is André Pardal. You can contact me in Portuguese or in English

# Who I am
I'm a friendly person with interests in technology, fintech, market economies & gaming.
After work I read about Ethereum & Token related news (Technology side), develop some smart contracts and try to stay up to date with Javascript development practices.

I hope to meet people with interest or ideas for blockchain/smart contracts use cases in MobilityHackLisbon

# What I do
I'm a fullstack developer with focus on front end javascript in my day job.
My strong programming languages are Javascript & Java but I also know Vuejs, Nodejs, HTML, a little of ReactJs, Css.

Blockchain related - I can develop in Solidity ( Ethereum programming language for smart contracts) and create for example Tokens, I Owe You contracts, create Ethereum blockchain clones

# Let's talk
Twitter - https://twitter.com/AndreCPardal
Slack group MobilityHackLisbon 
Linkedin - https://www.linkedin.com/in/apardal/
Here in github with comments

**Comment by sargupta** [comment]
Hi!
I needed a developer for Blockchain Empowered Vehicles Challenge. Will need to write smart contract. I think you would be the perfect fit. I am a Data Scientist (Python), would you like to be part of my team?

**Comment by acpardal** [comment]
Hi @sargupta we can talk on slack
